// <auto-generated />
using System;
using Advanced.NET_Labb3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Advanced.NET_Labb3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Advanced.NET_Labb3.Models.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("InterestDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InterestTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            InterestDescription = "Sitta och göra sidoprpjekt",
                            InterestTitle = "Programmering"
                        },
                        new
                        {
                            InterestId = 2,
                            InterestDescription = "Cykla mountainbike",
                            InterestTitle = "Cykla"
                        },
                        new
                        {
                            InterestId = 3,
                            InterestDescription = "Kitesurfa nere i viken",
                            InterestTitle = "Surfa"
                        });
                });

            modelBuilder.Entity("Advanced.NET_Labb3.Models.JoinTable", b =>
                {
                    b.Property<int>("PersonInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonInterestId"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonInterestId");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("JoinTables");

                    b.HasData(
                        new
                        {
                            PersonInterestId = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 2,
                            InterestId = 2,
                            PersonId = 2
                        },
                        new
                        {
                            PersonInterestId = 3,
                            InterestId = 3,
                            PersonId = 3
                        });
                });

            modelBuilder.Entity("Advanced.NET_Labb3.Models.Link", b =>
                {
                    b.Property<int>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinkId"));

                    b.Property<int>("PersonInterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("joinTablePersonInterestId")
                        .HasColumnType("int");

                    b.HasKey("LinkId");

                    b.HasIndex("joinTablePersonInterestId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            LinkId = 1,
                            PersonInterestId = 1,
                            Url = "https://example.com/programmering"
                        },
                        new
                        {
                            LinkId = 2,
                            PersonInterestId = 2,
                            Url = "https://example.com/cykla"
                        },
                        new
                        {
                            LinkId = 3,
                            PersonInterestId = 3,
                            Url = "https://example.com/surfa"
                        });
                });

            modelBuilder.Entity("Advanced.NET_Labb3.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumber")
                        .HasColumnType("int");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            FirstName = "Ermin",
                            LastName = "Husic",
                            PhoneNumber = 72222
                        },
                        new
                        {
                            PersonId = 2,
                            FirstName = "Oskar",
                            LastName = "Johansson",
                            PhoneNumber = 7222322
                        },
                        new
                        {
                            PersonId = 3,
                            FirstName = "Jonathan",
                            LastName = "Bengtsson",
                            PhoneNumber = 7245645
                        });
                });

            modelBuilder.Entity("Advanced.NET_Labb3.Models.JoinTable", b =>
                {
                    b.HasOne("Advanced.NET_Labb3.Models.Interest", "Interest")
                        .WithMany("JoinTables")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Advanced.NET_Labb3.Models.Person", "Person")
                        .WithMany("JoinTables")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Advanced.NET_Labb3.Models.Link", b =>
                {
                    b.HasOne("Advanced.NET_Labb3.Models.JoinTable", "joinTable")
                        .WithMany("Links")
                        .HasForeignKey("joinTablePersonInterestId");

                    b.Navigation("joinTable");
                });

            modelBuilder.Entity("Advanced.NET_Labb3.Models.Interest", b =>
                {
                    b.Navigation("JoinTables");
                });

            modelBuilder.Entity("Advanced.NET_Labb3.Models.JoinTable", b =>
                {
                    b.Navigation("Links");
                });

            modelBuilder.Entity("Advanced.NET_Labb3.Models.Person", b =>
                {
                    b.Navigation("JoinTables");
                });
#pragma warning restore 612, 618
        }
    }
}
